### ISSUE TITLE
Node gets overloaded when processing multiple requests

### ISSUE THREAD

**Issue by M0ebiu5** [meeki007/node-red-contrib-facial-recognition#19] opened 2020-12-23 12:45 UTC
If i send multiple files to the node to be recognized (not learning), sometimes node-red crashes, but if not, it still processes all requests before starting to return the results.  

The desired behavior would be, that each request will be handled only after the previous recognition result has been sent.

**Comment by wnasich** [comment] 2020-12-23 12:57
You could resolve it by using a 'delay' node, It allows you to set the rate limit of message

**Comment by M0ebiu5** [comment] 2020-12-23 13:11
sure, i do it like that right now, but this is just not right...it should be message driven and not wasting time with delays...

**Comment by meeki007** [comment] 2020-12-23 13:32
@M0ebiu5 "...desired behavior would be, that each request will be handled only after the previous recognition result has been sent."

I thought about how to handle input to this node. I first thought was along your lines. But what do I do with all these input messages that are backing up while waiting for the current input message to finish?

I could create a que but then ram is at a premium on most devices. And the more input images i put in que the less ram for tensorflow to do its processing.

I could drop requests made until the current input image is finished processing but that adds overhead in time and having to deal with context set / get also overhead.

The solution I came up with is multiple workers and leave it up to the user. processing time to complete is given to you in the payload out.  See ---->  [https://github.com/meeki007/node-red-contrib-facial-recognition#Heavy_image_processing_or_mjpeg_video_stream](https://github.com/meeki007/node-red-contrib-facial-recognition#Heavy_image_processing_or_mjpeg_video_stream)

Now I could not be seeing the solution. If im missing something or a better option to handle this let me know.

**Comment by M0ebiu5** [comment] 2020-12-23 14:02
@meeki007 look, currently it is slower or even crashes - so that doesnt sound like a good solution...

If there are multiple request messages, why not just let the system handle it? Node-red knows how to deal with messages, queues etc. If there are more input messages waiting to be processed, where is the problem? Also afaik node-red is single threaded, so multiple workers would only increase memory load, but not throughput i think - did you measure it and how much faster was the multiple workers flow?

When using one node, subsequent requests block the previous requests from finishing, thats not good...

**Comment by meeki007** [comment] 2020-12-23 15:01
@M0ebiu5 "If there are more input messages waiting to be processed, where is the problem?"

The problem is with tensor flow hungry use of ram. The more messages that back up the less available ram for tensorflow to do its job.

@M0ebiu5 "did you measure it and how much faster was the multiple workers flow"
I never said it was faster. All this does is break up how hard your hammering one tensorflow. It does increase ram usage. Less likely to crash it.

I willing to bet when you crash your pushing too hard on the tensorflow back end. I cant write a catch that will allow me to warn users on this one as it is not an error until its too late.

Show me your node-red output / run log and im sure you have ram warning issues.
example: Allocation of 377318400 exceeds 10% of system memory

I do let node red handle the messages. I can't get api for TensorFlow to give me anything I can use in a catch statement to send to a user or stop it from crashing if you send it too many / too large of an image for your hardware. 

if you find a way to catch the warning let me know and I can improve add a check and maybe stop these crashes.

Stop sending it too big or too many images for your hardware is the solution for now.
If anyone can see a fix to this problem let me know / send a pull request.

**Comment by meeki007** [comment] 2020-12-23 15:51
@M0ebiu5
I have a solution that may be what your looking for and your line of thinking help me create a new flow example.

Ive updated the documentation ---> [https://github.com/meeki007/node-red-contrib-facial-recognition#Simple_Queue_Method](https://github.com/meeki007/node-red-contrib-facial-recognition#Simple_Queue_Method)
![q-method.jpg](https://raw.githubusercontent.com/meeki007/node-red-contrib-facial-recognition/main/doc/q-method.jpg)

**Comment by M0ebiu5** [comment] 2020-12-23 15:52
Sorry, i'm not into node-red programming, but i would assume one has to accept an incoming message (request) and as long as one does not accept a message, node-red takes care of that pile of incoming msgs and waits for the node...

About the ram warning: i couldnt find anything about it in the logs - the machine has 14gb ram and i was "hammering" it with apr. 100 images á 150kB. 

Anyway, i will just keep limiting the input msgs...thanks for your time!

**Comment by meeki007** [comment] 2020-12-23 15:56
Oh you have plenty of ram to use the above method I outlined.

**Comment by M0ebiu5** [comment] 2020-12-23 16:01
I will try your suggestion with the queue, it looks better than the delay - although it needs another external node...thanks!

**Comment by M0ebiu5** [comment] 2020-12-23 16:15
Just if you dont know: you could use `node-red-contrib-fs` to iterate over a directory and feed a ton of files into you node easily :)

**Comment by meeki007** [comment] 2020-12-23 16:18
I love that node :) I use it all the time. but it is quicker to write your own while loop . but not by much. only matters when getting hundreds of thousands of images or videos.

**Comment by meeki007** [comment] 2020-12-23 16:23
I'm curious. what are you doing???? I like to know what people are up to with this node. It gives me ideas besides my own project of automatic entry to my front door and email alert if someone is seen on a camera that is not on the known list.

**Comment by M0ebiu5** [comment] 2020-12-23 16:27
I also try to use it on my doors :) For now i will also check for the wifi mac of the mobile of the recognized person, but if i can get it to work reliable and with 2 cameras, the door should unlock - and send a msg with the picture of the person...

**Comment by meeki007** [comment] 2020-12-23 16:31
make sure you use IR only camera or filter or someone can hold a picture up to the camera and it will trick it. 

IR pass filter. You can buy thin plastic sheet you can cut and put over the camera lens inside the tablet. Add a IR light (people cant see it).

or you can go hack method if you have an old floppy disk hanging around

http://the-print-guide.blogspot.com/2010/09/using-old-floppy-disks-as-photography.html

**Comment by M0ebiu5** [comment] 2020-12-23 16:37
Thanks for the hint!
It's not that easy here, because my cameras are app 1m behind glass doors - so the picture has to be as big as my head (maybe an ipad would do it). To increase security i would use a second camera 90° on the side.

Another idea would be to try to recognize a phone on the image (which shouldnt be difficult, if someone is holding it up with the image :)

**Comment by M0ebiu5** [comment] 2020-12-24 12:48
I've did some tests (apr. 200 files) with another node `node-red-contrib-tfjs-coco-ssd` and it shows the same behavior (accepting all messages, no output and then node-red restarts).

So it seems that it could be something inside of node-red or maybe tensorflow causing this, but its not unique to your node.

There is also no indication in the logs, why the restart occurs - maybe some kind of timeout while the node eats up all cpu...
Not good, but certainly interesting...

**Comment by meeki007** [comment] 2020-12-24 13:22
Yep I looked into this issue and its deep in the @tensorflow/tfjs-node I would love to catch this error but I don't have the skill/time/want to dig in the innards of that repo. Sometimes it does send msg out but it is not covered by the @tensorflow/tfjs-node api so I can catch it.

**Comment by meeki007** [comment] 2020-12-24 13:32
"...it shows the same behavior (accepting all messages, no output and then node-red restarts)."

Ive seen this because of:
bad image file
image file is labeld as .jpg but is a png
image is too fricken big
image is not a image but label as one

it is a pain to hunt down every image in a folder and check to see if its correct.

**Comment by M0ebiu5** [comment] 2020-12-24 14:01
hmm i doubt that an image is faulty, because the only image source is my hikvision ipcam and any image it records is resized and stored in node-red via jimp. 
But i will just duplicate a good one to exclude even that possibility...

**Comment by meeki007** [comment] 2021-01-04 15:30
closing for now....

**Closed by meeki007** 2021-01-04 15:30 UTC
